version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: logs_user
      POSTGRES_PASSWORD: logs_password
      POSTGRES_DB: logs_db
    networks:
      - app-net

  backend:
    image: hichemmlh/logmein-backend:latest
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks:
      - app-net

  frontend:
    image: hichemmlh/logmein-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-net

networks:
  app-net:
    driver: overlay
