name: LogMeIn CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: logs_user
          POSTGRES_PASSWORD: logs_password
          POSTGRES_DB: logs_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 1. Checkout du code
        uses: actions/checkout@v4

      - name: 2. Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: 3. Installation des dépendances
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - name: 4. Exécution des tests automatisés (Pytest)
        env:
          DB_HOST: localhost
          DB_NAME: logs_db
          DB_USER: logs_user
          DB_PASSWORD: logs_password
          DB_PORT: 5432
        run: |
          cd backend
          sh run_tests.sh

      - name: 5. Scan de sécurité Trivy (Vulnerabilities)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'

      - name: 6. Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 7. Build and push backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/logmein-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/logmein-backend:latest

      - name: 8. Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/logmein-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/logmein-frontend:latest

      - name: 9. Copie du fichier docker-compose sur AWS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/ubuntu/"

      - name: 10. Déploiement sur AWS (Docker Swarm)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stack deploy -c /home/ubuntu/docker-compose.prod.yml logmein
