name: LogMeIn Full CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test-and-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 1. Setup Python & Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: 2. Automated Tests (Pytest)
        run: |
          cd backend
          python -m pytest test_api.py

      - name: 3. Vulnerability Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '0'

  deploy:
    needs: test-and-security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 4. Build & Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t hichemmlh/logmein-backend:latest ./backend
          docker build -t hichemmlh/logmein-frontend:latest ./frontend
          docker push hichemmlh/logmein-backend:latest
          docker push hichemmlh/logmein-frontend:latest

      - name: 5. Remote Deploy to AWS Swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            docker stack deploy -c docker-compose.prod.yml logmein
