name: LogMeIn Full CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test-and-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Automated Tests (Pytest)
        run: |
          cd backend
          pip install flask flask-cors psycopg2-binary pytest
          python -m pytest test_api.py
      - name: Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          exit-code: '0'

  deploy:
    needs: test-and-security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Push
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t hichemmlh/logmein-backend:latest ./backend
          docker build -t hichemmlh/logmein-frontend:latest ./frontend
          docker push hichemmlh/logmein-backend:latest
          docker push hichemmlh/logmein-frontend:latest

      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # On recrée le fichier sur le serveur
            cat <<EOF > docker-compose.prod.yml
            $(cat docker-compose.prod.yml)
            EOF
            docker stack deploy -c docker-compose.prod.yml logmein
